version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
    environment:
      - ML_SERVICE_URL=http://ml_service:8002
    networks:
      - ventiglobe-network

  ml_service:
    build: 
      context: ./ml_service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./ml_service:/app
      - ./ml_data:/app/data
    environment:
      - BACKEND_URL=http://backend:8001
    networks:
      - ventiglobe-network

volumes:
  postgres_data:

networks:
  ventiglobe-network:
    driver: bridge 